syntax = "proto3";

package Kaleido.Grpc.Categories;

import "models.proto";

service GrpcCategories {
    rpc GetCategory(CategoryRequest) returns (CategoryResponse);
    rpc GetAllCategories(EmptyRequest) returns (CategoryListResponse);
    rpc CreateCategory(Category) returns (CategoryResponse);
    rpc UpdateCategory(CategoryActionRequest) returns (CategoryResponse);
    rpc DeleteCategory(CategoryRequest) returns (CategoryResponse);
    rpc GetCategoryRevision(GetCategoryRevisionRequest) returns (CategoryResponse);
    rpc GetAllCategoryRevisions(CategoryRequest) returns (CategoryListResponse);
    rpc GetAllCategoriesFiltered(GetAllCategoriesFilteredRequest) returns (CategoryListResponse);
}

